version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
     - "5000:8080"
    depends_on:
     - "postgres_db"
    networks:
      - aspnetcoreapp-network

  postgres_db:
    container_name: 'postgres'
    image: postgres
    ports:
     - "5432:5432"
    environment:      
      POSTGRES_PASSWORD: Qwerty1!
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge