version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
     - "5000:8080"
    depends_on:
     - "postgres_db"
    networks:
      - aspnetcoreapp-network

  postgres_db:
    container_name: 'postgres'
    image: postgres
    environment:      
      POSTGRES_PASSWORD: Qwerty1!
    networks:
      - aspnetcoreapp-network

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  #   container_name: elasticsearch
  #   environment:
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.5.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

networks:
  aspnetcoreapp-network:
    driver: bridge

# volumes:
#   elasticsearch-data:
#     driver: local